---
- name: My First Project With Ansible
  hosts: localhost
  vars: 
    myname:
      - Seif
      - Sherif
      - Ahmed
  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "This is My First Ansible Project"

    - name: Execute date command
      command: date

    - name: Print Var
      ansible.builtin.debug:
        msg: "My name is: {{ myname[0] }}"

    - name: Execute Bash Script File
      ansible.builtin.shell: /path/bash.sh
        cmd: ./ansible.sh





      
